### ISSUE TITLE
Unavailable release tarballs

### ISSUE THREAD

**Issue by Coacher** [wayland-wall/wayland-wall#1]
Hello.

There are no tags in repo. Ok...
README says that tarballs are here: https://www.eventd.org/download/wayland-wall/. HTTP 404...

Please either add tags or provide tarballs by other means.

**Comment by sardemff7** [comment]
There are currently no releases, as you noticed with the empty tag list.
What do you need a tarball for?

**Comment by Coacher** [comment]
I was planning to introduce the next release of eventd into the Gentoo main repo. Wayland support in eventd as you know requires wayland-wall. I need smth non-live per Gentoo rules.

**Comment by sardemff7** [comment]
Wayland support in eventd needs [weston-wall](https://github.com/wayland-wall/weston-wall) plugin and only works in Weston and my unreleased WayHouse.
It’s probably not worth the effort to include this support right now. I’ll start releases once the preliminary work on libweston is done to kind of support shared plugins.

**Comment by Coacher** [comment]
Ok, that's fine with me. Thank you for the info!

P.S. If you say eventd actually wants weston-wall, then this is probably a typo: https://github.com/sardemff7/eventd/blob/977ba0ea808cb6239b35fb296e12ede909a8b69d/configure.ac#L280

**Comment by sardemff7** [comment]
I say that eventd-nd/wayland will only work with a server-side implementation, and the only one available is in weston-wall (and orbment-wall), nothing like the coverage the nd/xcb backend has.

**Comment by Coacher** [comment]
Ah, I see. Thanks for the clarification.
